:PROPERTIES:
:ID:       F0A6402E-2C73-457D-A25C-0EF98283F992
:END:
#+title: find
#+category: find

NOTE: This is based on GNU find.

# Syntax

`find [-H] [-L] [-P] [-D debugopts] [-Olevel] [starting-point...] [expression]`

# Description

Searches the directory tree rooted at each `starting-point` by evaluating
`expression` from left to right, according to the rules of precedence in
[Operators], until the outcome is known (the LHS is false for `and` operations,
true for `or`), at which point `find` moves on to the next file name.

# True options

## Symbolic links

`-H`, `-L`, `-P`

## Debugging find

`-D debugopts`

TODO: Test `-D exec`

# Starting points

Default value: `.`

Should be prefixed with `/` or `./`, according to the man page, but what about
`../` or `~/`? TODO: How do quotes affect expansion of `.`, `..`, and `~/`?


# Expression

Default value: `-print`

The `expression` is identified by arguments beginning with `-` (expression
options) or the arguments `(` or `!` (i.e., grouping and negation).

## Positional options

Affect only subsequent tests and actions.

Always return true.

```
-regextype type     Select the regex syntax. See `-regextype help` for
                    available syntax.
```

## Global options

Affect the operation of all tests and actions specified.

Always returns true.

```
-depth              Process directory's contents before directory itself.
                    Implied by the -delete action.
-help               Print summary of usage and exit.
-maxdepth levels    Number of directories below starting-point to descend. 0
                    means to only process the starting-points.
-mindepth levels    Do not apply tests or actions above levels. 1 means process
                    all files below the starting-points.
```

## Tests

Truth status is based on the outcome of the test.

Numeric arguments can be specified as `+n`, `n`, and `-n` for greater than,
exactly, and less than `n`, respectively.

```
-empty              File or directory is empty.
-executable         Matches executable files and searchable directories.
-false              Always false.
-name pattern       Basename of file matches pattern. Slashes not allowed. *, ?,
                    and [] may match a . at the start of the basename. Braces
                    are not special. Enclose in quotes to prevent shell
                    expansion when using a globbed pattern to match files. Or
                    escape globbed characters with a backslash. See e.g., the
                    Non-Bugs section of the man pages.
-path pattern       Filename matches shell pattern. / and . are treated
                    literally. Use -prune to negate the pattern (i.e., ignore
                    it any its children). E.g.,
                    find . -path ./src/emacs -prune -o -print
                    will print any file and directory under . but not under
                    ./src/emacs. pattern must start with one of the
                    starting-points. An absolute filename will only match an
                    absolute starting-point. pattern cannot end in /.
-regex pattern      Like -path with a regex pattern instead of a shell pattern
                    (e.g., .* instead of *). Like -path, this is match on the
                    whole path: .*bar. or .*bar.*3 match ./fubar3, but f.*r3
                    does not match.
-samefile name      File refers to same inode as name. If -L is in effect, this
                    can include symbolic links.
-true               Always true.
-type c             File is of type c, which can be b (block), c (character), d
                    (directory), p (named pipe/FIFO), f (regular file), l
                    (symbolic link), s (socket). Can be a comma-separated list
                    of more than one type.
```

For case-insensitive variants, see `-iname`, `-ipath`, and `-iregex`.

## Actions

Truth status is typically based on the success of the action.

```
-delete                 True if removal succeeded. To test first, replace
                        -delete with -depth, since it is implied by -delete.
-exec command ;         Executes command for each file being processed. True if
                        0 status is returned. All following arguments to find
                        are taken as command arguments until ; is encountered.
                        {} is replaced by the current filename being processed.
                        ; and {} may need to be escaped via \ or quoted to
                        prevent shell expansion. The command is executed in the
                        starting directory, presumably meaning the filename is
                        relative to that directory.
-exec command {} +      Runs the command with selected filenames appended,
                        rather than once per filename. Always returns true. {}
                        can only be specified once and needs to be quoted when
                        invoking find from a shell.
-execdir command ;
-execdir command {} +   Like -exec, but the command is run from the subdirectory
                        containing the matched file. For the {} + variant, only
                        files in the same subdirectory are appended to each
                        command invocation.
-ok[dir]                Like -exec[dir] with a prompt. Truth value is false if
                        the user responsds negatively to the prompt.
-print                  Print full filename followed by newline.
-print0                 Use for files with newlines or apparently other
                        whitespace in the filename when feeding output of find
                        to another program. See -0 option of xargs and the
                        examples.
-printf                 See man page.
-prune                  Returns true. Do not match item and if item is a
                        directory, do not descend into it.
-quit
```

## Operators

Default value (whenever an operator is absent): `-a`

Used to join together items within the expression.

```
(expr)          Force precedence. You will usually need to quote or escape
                these with \.
! expr          True if expr is false. Probably need to escape this.
expr1 expr2     Implies -a.
expr1 -a expr2  Do not evaluate expr2 if expr1 is false.
expr1 -o expr2  Do not evaluate expr2 if expr1 is true.
expr1 , expr2   Always evalute both expressions. The value of the list is the
                value of expr2.
```

`-a` has higher precedence than `-o`. E.g.,
`find . -name afile -o -name bfile -print`
is equivalent to
`find . -name afile -o \( -name bfile -a -print \)`
meaning afile will never print. To achieve that, use
`find . \( -name afile -o -name bfile \) -print`
meaning that only filename matching afile or bfile prints.

# More examples

```
find /tmp -name core -type f -print0 | xargs -0 /bin/rm -f
    Remove files named core within /tmp or its subdirectories, handling
    irregular filenames correctly

find . -type f -exec file '{}' \;
    Execute file on files under PWD. Note the escaped {} and \.

find /sbin /usr/sbin -executable \! -readable -print
    Find executable but unreadable files. Notice the escaped !.

cd /source-dir
find . -name .snapshot -prune -o \( \! -name '*~' -print0 \)|
cpio -pmd0 /dest-dir
    The use of -prune -o \( ... -print \) is common. -prune always returns true,
    so you place the expression and action for files you want to match on the
    right.

find repo/ \( -exec test -d '{}'/.svn \; -or \
-exec test -d {}/.git \; -or -exec test -d {}/CVS \; \) \
-print -prune
    -exec only returns true if the command returns status 0. The test command
    returns 0 when the test is true, so only the directories containing a VCS
    folder are matched. -prune prevents descent into these directories. Note
    that if repo/ (or a starting-point you specify) contains a .git directory,
    find will not descend into ANY subdirectories. To avoid this, you need to
    use -mindepth -1, as below.

find -mindepth 1 -exec test -d '{}'/.git \; -print -prune
    See previous example.
```

# Exit Status
Returns 0 if all files are processed successfully, greater than 0 if errors
occur. Errors may stop find immediately, halting any invocations specified by
-exec or -execdir.

# Miscellaneous

To avoid unwanted side effects from malicious filenames, see the
`Unusual Filenames` section of the man pages.

The `Environment Variables` section of the man pages describes which ones affect
find behavior such as collation.
