:PROPERTIES:
:ID:       7FA32AB4-979E-4067-993B-EA1A2F465C9D
:END:
#+title: Voting
#+category: Voting

According to https://elections.saccounty.net/VotebyMail/Pages/default.aspx, I can track my ballot at ballottrax.net. The site has a joint login/registration button that cross-references your name, birthdate, and zip code. Presumably someone else could login this way and change my email, text, and phone information that is used to notify me about changes to my ballot status throughout the entire balloting process, from printed to accepted. This wouldn't affect my ballot delivery, but it could keep me from learning about a delayed ballot. It would be up to me to check that information if no updates were provided to me within the expected time frame for my ballot to be mailed to me.

According to https://howto.vote/vote/en/ca.html, I should be mailed a ballot by no later than 29 days before November 3, 2020 (October 5), for the 2020 election. In fact, all registered voters in 2020 will be mailed a ballot without application for vote-by-mail in CA. (I have already set my voter preferences to vote by mail.)

Presumably ballots are accepted within 17 days after Election Day, but does that mean a Presidential Election could potentially be flipped after 17 days?

My voting history with Sacramento County can be viewed at:
https://pollingplacelookupen.saccounty.net/Language/EN


I was eligible to vote after 3/25/2010, but my registered history goes back only to Nov 8 2016. I may have voted in SBC prior to this.

* Match your indicated election choices against election results, and do a writeup.
Results of past elections in Sacramento can be viewed at https://elections.saccounty.net/ElectionInformation/Pages/ResultsPrevElect.aspx.

* Find a copy of your signature in my voter registration record. For the ballot to count, it must match my ballot signature. I do not have a consistent signature.
According to my Sacramento County voting history, my 3/3/20 Primary ballot was "challenged." They "Vote by Mail REason" says "Contact Office." But the FAQ (https://elections.saccounty.net/VotebyMail/Pages/SAC_VRE_DF_Vote_Absentee.aspx) claims they will send me a Signature Verification Statement to complete if the signature if the reason a ballot is challeneged. They may have tried reaching me, and I had moved or lost the mail. Or some other clerical error on their end.

Update: The link changed to the one currently listed for voter history, the webpage has been restructred, and it says my ballot for 3/3/20 was accepted.

** Find who to contact
The link above lists the following contact information: https://www.saccounty.net/ContactUs/Pages/default.aspx

* Study upcomging ballot proposals and elections
https://ballotpedia.org/Sample_Ballot_Lookup
Nothing is displayed at https://elections.saccounty.net/ElectionInformation/Pages/what-is-on-my-ballot.aspx.
Some information at https://www.cityofsacramento.org/Clerk/Elections
https://www.sos.ca.gov/elections/

Now that I think about it, who prints my specific ballot guide? With all of the State AND local initiatives and candidates? If I find this, I can find what my ballot might look like! If I can't find that I can cross-reference the results of looking up all of my districts--there are a lot of them--via https://pollingplacelookupen.saccounty.net/LookupPollingPlace_VoterDistrict.aspx.

https://elections.saccounty.net/Pages/default.aspx
 - The link to the Online County Voter Information Guide just takes me to my past voting history. There is no guide available. Is it not ready yet?

https://elections.saccounty.net/ElectionInformation/Pages/OptionsforReceivingYourSampleBallotBooklet.aspx
 - Claims the Online County Voter Information Guide can be located at the link above, but also gives em the choice to opt-in to receiving a printed guide. Since the online guide isn't available, is the printed? When are they released? I'm guessing closer to November (it is only August, 2020, as I write this.)

The card that was sent to me in the mail was from County Of Sacramento's Votre Registration and Elections [Office] at 7000 65th St, Ste A, Sacramento, CA. I think they operate the elections.saccounty.net site, or at least are plugged into it somehow.
