:PROPERTIES:
:ID:       4e97c681-1fd6-423d-b31a-2965b950822c
:END:
#+title: Accessibility
#+filetags: :work:
#+category: work

* root
** TODO Review [[http://itb/docs/custservice/webshop/webcontent_guides.htm][ITB Job Aids]]
** Meetings
*** 2020-07-21: Meeting on biggest challenges of ADA process
- Tables require a lot of effort, especially when the table editor is required
  - Nested row and column headers
  - Merged cells
  - References and foonotes
- When a page prevents you from tagging it, remove the page and try
  again. Sometimes this will fix the issue.
- IT is identifying issues with our ADA documents through the PDF reader
  tool. Using that can give you an idea of potential roadblocks to approval of
  your document.
** Training
*** 8/21/20: ITB Training Notes
**** Word
***** Alt Text
In Word: Format Picture>Layout & Properties>Alt Text>Description field. Ignore Title field.
Keep it short.
Don't duplicate nearby text.
Avoid phrases such as "grahpic of...". Screen readers state this already.
Don't add alt text to decorative images.
Don't add alt text if a descriptive caption exists.
If the figure itself contains text, consider using that text as the alt text.
For complex images like graphs, provide a short summary of what the data describes in alt text and either include a data table or describe the image at length in the document's normal (non-alt) text. Data tables should be placed inline after a chart; otherwise, tables should be placed in an appendix, and a link to the table should be provided directly after the chart.
Images should be wrapped (Wrap Text) In Line with Text, else the screen reader will skip the image because the image will not be included in the PDF Tags structure when exported to PDF. (Q: Can't this be fixed by manually adding a tag and specifying the reading order?)
***** Hyperlinked text
Screen readers read linked text, so it is best to avoid listing the raw URL and instead provide a description ("Text to Display" when editing/inserting a link)
Lined text should be descriptive, concise, unique, and visually distinct
Use Normal text style for full URLs (i.e., the raw link if provided). For documents designed for printing, you should provide the raw link. For a list of links, you can make each list item linked text with hyperlink formatting, then provide the Normal raw link underneath without a bullet.
***** Contrast
If not using white background and black text, use the [[https://webaim.org/resources/contrastchecker/][WebAIM Contrast Checker]] to check that contrast between background and foreground colors have a contrast ratio of greater than 4.5:1, as defined by WCAG.
Avoid conveying information via color. If you use color to differentiate data on a graph, also provide an alternative such as document text (non-alt text) or a data table.
***** Writing
****** Tips
Write for your audience.
Focus on the most important information.
Use jargon only when necessary.
Use active verbs and personal pronouns.
Explain unknown initialisms and acronyms.
****** Tools
Enable Word's Show Readability Statistics preference.
Aim for sentences per paragraph of 5 or less and words per sentence of 20 or less. Use active voice, especially when Passive Sentences score is >20%. Revise document to reduce size of sentences (words and/or syllables) if Fleisch Reading Ease score is >60 or if Flesch-Kincaid Grade Level score is >8. The above may not apply to documents targeted toward more sophisticated audiences.
***** Legibility
Keep font size at 11 points or higher.
Lines should contain between 60-100 characters.
Ensure sufficient spacing between characters and words.
Left-align paragraphs.
Reserve underlines for links.
The defaults for Word usually meet these criteria.
***** Tables
Create a table. Click on the table. On Windows: Table Tools>Design or Table Tools>Layout. Not to be confused with the non-contextual Design and Layout tabs on Windows. On Mac: Table Design, and Layout. In the first row, make sure that the Header Row checkbox is checked. If the first column is row headers, make sure that the First Column checkbox is checked in each cell in the first column.

Note that this is a piss poor name for this option. Why not Header Column?

Tables cannot have multiple row and/or column headers, and table structure needs to be simple.

Mark row and/or column headers visually, using bolding and sufficient color contrast.

The training recommends headings prior to tables but makes no mention of captions.

Does not recommend using tables to organize text in columns. I'm not sure whether this affects the Rmd-generated PDFs of TGA evaluations. Our Word form did use tables, but we don't make the PDF evaluations accessible, and our interal AP forms are not published externally, in contrast to Registration's copy of the forms.

****** Repeat Headers Across Multiple Pages
The Layout tab for tables>Repeat Header Rows.
**** Powerpoint
[[https://templates.office.com/en-us/accessible-powerpoint-template-sampler-tm16401472?ui=en-US&rs=en-US&ad=US][Accessible templates from Microsoft]]
Slide titles are presented as headers by screen readers
If you select a different layout for a non-blank slide, PPT will try to fit contents to the new layout; however, it may be easiest to simply create a new slide with the desired layout and add the content.
***** Slide Master
Used to style all slides or create/modify layouts.
The first slide in Slide Master is the Master Layout that affects all slides. Below this are individual layouts.
Placeholders are inserted via Slide Master. A Text Placeholder is distinct, e.g., from a Text Box. Reading order should be checked when non-placeholders are present on a slide. The last object added to a slide is last in reading order. Arrange tools like "Send to Front" change reading order.
To edit the reading order of objects on a slide: Home>Arrange>Selection Pane. The reading order in the Selection Pane is bottom to top. The numbers to the right of each placeholder or content types isn't relevant to the reading order. Simply drag items in the Selection Pane into the desired order, bottom to top.
Use large text, simple animations, avoid cluttering slides with visuals, use concise language, and don't use color to convey information.
Caption videos and provide a transcript of audio used in your slides.
**** Evaluating Accessibility
***** To check accessibility
PC: File>Info>Check for Issues>Check Accessibility
Mac: Review>Check Accessibility
***** Accessibility Checker panel
****** Inspection Results
******* Errors
E.g., an image that is missing alternative text
******* Warnings
E.g., a table that has merged or split cells.
E.g., a warning to "Check Reading order" on a PPT slide where content was added.
******* Tips
E.g., duplicate slide titles [can make navigating slide titles/headers difficult for the end-user]
****** Corrections
Click on an item in Inspection Results to jump to the location of the error, warning, or tip.
Addressing the issue will remove the item from the Inspection Results.
***** Manual checks
Needed for many accessibility issues not flagged by the accessibility checker. E.g., headings created by changing text apperance, instead of using a Style.
***** Filenames
Filenames are read by screen readers when navigating to the document.
Hyphens and the capitals in camelCase are treated as the start of a separate word by screen readers. Other special characters should be avoided.
***** Titles
The title of a document should be similar to Heading 1.
****** Adding a title
Windows: File>Properties>Title field. Enter the title here.
Mac: File>Properties>Summary>Title field. Enter the title here.
**** Creating PDFs
Creating an accessible PDF can be done one of two ways:
- from the Acrobat tab>Create PDF in Word
- from within Adobe Acrobat Pro DC, File>Create>PDF from file. This method must be used for PPTs, as the Acrobat tab in PPT doesn't create accesible PDFs.
On Mac:
- If using Word, make sure Acrobat>Preferences>"Prompt for using Adobe Create PDF cloud service" is checked.
- If using Adobe Acrobat Pro, make sure File>Create>PDF from File>"Use Adobe Create PDF cloud service" is checked.
Avoid creating by:
- printing to PDF
- saving as a PDF.
These options can discard document structure or other accessibility information.
***** NOTE
Module 3>Quiz 3 covered information not apparently provided in the training guides. You may need to review the quiz for the final exam.
A) Module 4>Section 1 covers some of these questions. E.g., in discussing the visual "layer" of a PDF, it is mentioned that PDFs display the same across different "device types" and screen sizes. In Module 3>Quiz 3, the answer to a question about the benefits of a PDF is that it displays the same across different "hardware".
**** PDF
Source files for PDFs need to be made accessible. Recommends exporting PDF to Word via Acrobat>File>Export to>Microsoft Word>Word Document (or Micrsofot PowerPoint Presentation for PPTs)
- I wonder if this mechanism would better preserve tables and images, which was a big issue with the 2018 annual VOC report.
***** 3 layers
****** Visual
Layout and apperance (vague, not sure I understand)
Ignored by screen reader
****** Content,
Text with basic formatting like fonts and colors
****** Tags
Document structure and reading order
To show tags pane, right-click navigation pane, then show the tags pane.
Claims the screen reader will read the document according to tag pane order.
Apparently the reading order tool shows the order of the content layer.
***** Check Accessibility
****** Steps 1 and 2: Accessibility>Full Check (Mac) or Accessibility Check (Windows) / Reparing Tag Structure
******* Document
******** Tagged PDF - Failed.
Only fixable in Windows, not on Mac. Bummer, Mac.
********* To fix (method depends on how you created PDF, I guess--see approved methods above):
********** If PDF was created from within Word
Windows>Word>Acrobat tab>Preferences>Enable Accessibility and Reflow with tagged Adobe PDF. Then re-export as PDF using the approved Word export method.
********** If PDF was created from Word or PPT file from within Acrobat
Windows>Acrobat>Edit>Preferences>Categories>Convert to PDF>Microsoft Office Word>Edit Settings>check "Enable accessibility and reflow". Then re-export as PDF using the approved Adobe export method.

******* Page Content
******* Forms
******* Alternate Text
Images in the PDF will be marked with an X across it and truncated alt text at the top (or "Figure - No alternate text exists.").
Decorative figures will fail the accessibility check due to lack of alt text. Leave the failure as-is. In newer versions of Word, you can mark images/figures as decorative and leave the Alt Text Description field blank; otherwise, use Acrobat to hide images. In the Reading Order tool, mark the decorative figures as Background/Artifact. This removes the image from the tags pane structure tree.
******* Tables
Tables must identify headers and have proper Scope (i.e., column or row). Scope must be manually added.
Header cells have red background. Data cells have grey background.
You can hold the left mouse button and drag along the _inside_ of multiple cells you want to select. Zoom in to make this process easier.
- This is an alternative to SHIFT!!!!!!!!! Why didn't I know about this?!?!?!?!?
Note that the example in Module 4>Section 3 has an odd definition of row headers. Ask Ryan about this.
Upper left corner of table needs proper scope. If empty, it should be a data cell, not a header cell.
******* Lists
******* Headings
****** Untagged content
Not shown in screen reader. E.g., headers and footers from Word. Recommended to tag the footer text on the last page on which it appears, as Text/Paragraph.
***** Step 3: Repair reading order of content and tags
****** Content reading order (Reading Order tool)
The order given in the Reading Order tool
Used for the View>Zoom>Reflow, which the PDF as a single column for e.g. mobile devices.
Images from Word documents converted to PDF often have the wrong order within Reflow, but correct tag order.
_Use the "Show Order Panel" in the Reading Order tool_. I wasn't aware of this until the training.
May or may not propagate to tags order. Verify manually.
****** Tags reading order (Tags pane)
The order of the tags pane's elements.
Verify by expanding tags, starting at top, hitting down key, and verifying that the order on the PDF page cascades correctly.
